config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#new'
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:follow, :unfollow] do
  	member do
  		post :follow
  		post :unfollow
  	end
  end
	  
  resources :tweets do
    resources :likes
    resources :comments
    resources :retweets
      collection do
        get :my_tweets
      end
  end
	end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  #validates :content, presence: true

  def find_commenter
    User.find_by(id: user_id)
  end
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'

  belongs_to :followee, class_name: 'User'
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable , polymorphic: true#, inverse_of: :images
  has_one_attached :image
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/retweet.rb
class Retweet < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :retweets
  has_many :images, as: :imageable#, inverse_of: :tweet
  accepts_nested_attributes_for :images,reject_if: proc{|b| b[:image].blank?}

  validates :content, presence: true
  validates :content, length: { maximum: 140 }

  def is_already_like(user)
  	#debugger
  	Like.where(user_id: user.id, tweet_id: id).exists?
  end

  def find_like(user)
  	likes.find_by(user_id: user.id)
  end

  def is_retweet(user)
    Retweet.where(user_id: user.id, tweet_id: id).exists?
  end

  def find_who_tweeted
    User.find_by(id: user_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
  has_one :image, as: :imageable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users

  has_many :likes, dependent: :destroy
  has_many :retweets, dependent: :destroy
  has_many :comments, dependent: :destroy

  def is_following(user)
  	followees.include?(user)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_tweet

  def new
  	@comment = Comment.new
  end

  def create
    #debugger
    @comment = current_user.comments.create(comment_params)
    # @comment = @tweet.comments.create(content: comment_params[:content], user_id: current_user.id)
    respond_to do |format|
      format.html
      format.js{}
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :tweet_id)
  end

  def find_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end
 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@users = User.page(params[:page]).per(3)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_tweet, only: [:create, :destroy]
  
  def index
  end

  def create
  	#debugger
    @like = @tweet.likes.create(user_id: current_user.id)
    #redirect_to tweets_path
    respond_to do |format|
      format.html
      format.js{}
    end
  end

  def show
  end

  def destroy
    @like = @tweet.likes.find(params[:id])
    @like.destroy
    respond_to do |format|
      format.html
      format.js{}
    end
  end
  
  private
  def find_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end

  def likes_params
  	params.require(:like).permit(:tweet_id, :user_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :find_tweet, except: [:new, :create, :index, :my_tweets]
  
  def index
    @tweets = Tweet.where(:user_id => current_user.followees).or(Tweet.where(user_id: current_user.id))#.or(Reweet.where(user_id: current_user.followees))
    #@tweets = Tweet.joins(user: :following_users).where(users: {follows: {follower_id: current_user.id}}).distinct
  	#@tweets = Tweet.all
  end

  def my_tweets
    #debugger
    # @tweets = Tweet.joins(:retweets).where(user_id: current_user.id , retweets: {user_id: current_user.id})
    @tweets = Tweet.left_outer_joins(:retweets).where("tweets.user_id=? or retweets.user_id=?", current_user.id, current_user.id).distinct
    #@tweets =Tweet.find_by_sql("SELECT * FROM tweets INNER JOIN retweets ON retweets.tweet_id = tweets.id WHERE tweets.user_id = 13 OR retweets.user_id = 13")
    #@tweets = Tweet.joins("INNER JOIN retweets ON tweets.id = retweets.user_id").where(user_id: current_user.id)
    #@tweets =  current_user.tweets
  end

  def new
  	@tweet = Tweet.new
    1.times { @tweet.images.build }
  end

  def create
  	#debugger
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
    	flash[:alert] = 'Here is your tweet'
    	redirect_to tweet_path(@tweet)
    else
    	flash[:alert] = "Sorry! unable to upload your tweet "
      #render 'new'
      redirect_to new_tweet_path
    end
  end

  def show
  end

  def edit
  end

  def update
  	if @tweet.update(tweet_params)
  		flash[:alert] = 'updated'
  		redirect_to tweet_path(@tweet)
  	else
  		render 'edit'
  	end
  end
  
  def destroy 
    if @tweet.destroy
    	flash[:alert] = "Successfully! tweet deleted"
    	redirect_to new_tweet_path
    else
    	flash[:alert] = "Sorry! Enable to delete your tweet"
    	redirect_to 
    end
  end
  private

  def find_tweet
    @tweet = current_user.tweets.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:content, images_attributes: [:id, :image, :imageable_type, :imageable_id, :_destroy ])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def follow
  	new_follow = current_user.followed_users.new(followee_id: params[:id])
  	if new_follow.save
  		flash[:alert] = 'followed successfully'
  	else
      flash[:alert] = 'Sorry! couldnt follow'
  	end
    redirect_to root_path
  end

  def unfollow
    follow = current_user.followed_users.find_by(followee_id: params[:id])
    if follow.destroy
      flash[:alert] = 'Successfullyy unfollowed'
    else
      flash[:alert] = 'Sorry! couldnt unfollow'
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/retweets_helper.rb
module RetweetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

  def is_my_tweet(tweet)
    current_user.id == tweet.user_id 
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
   
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "/shared/navbar" %>
    <div class="flash-mesages">
      <%= render partial: "/shared/flash" %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-primary w-50 text-center my-2 ml-auto mr-auto">
    <%= msg %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-dark justify-content-between">
  <a class="navbar-brand ml-3 text-light">
    <i class="fa fa-twitter fa-lg p-1" aria-hidden="true"></i>Navbar
  </a>
	<% if user_signed_in? %>
	  <%= link_to 'Home',   home_index_path, class: 'text-light my-2 mr-4 float-sm-left' %>
	  <%= link_to 'Tweets', tweets_path, class: 'text-light my-2 my-sm-0 mr-4' %>
	  <%= link_to 'CreateTweet', root_path, class: 'text-light my-2 my-sm-0 mr-4' %>
    <%= link_to 'MyTweets', my_tweets_tweets_path, class: 'text-light my-2 my-sm-0 mr-4 red' %>
    <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class: 'css_class btn btn-outline-danger my-2 my-sm-0 mr-4', style: 'color:red' %>
  <% else %>
    <%= link_to 'Login', new_user_session_path, class: 'css_class btn btn-outline-success my-2 my-sm-0 mr-4', style: 'color:green'  %>
  <% end %>
</nav>
<!-- <i class="fa fa-user-circle-o float-right p-3 fa-2x" aria-hidden="true"></i> -->