config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#new'
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:follow, :unfollow] do
  	member do
  		post :follow
  		post :unfollow
  	end
  end
	  
  resources :tweets do
    resources :likes
    resources :comments
    resources :retweets
      collection do
        get :my_tweets
      end
  end
	end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  #validates :content, presence: true

  def find_commenter
    User.find_by(id: user_id)
  end
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'

  belongs_to :followee, class_name: 'User'
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable , polymorphic: true#, inverse_of: :images
  has_one_attached :image
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/retweet.rb
class Retweet < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :retweets
  has_many :images, as: :imageable#, inverse_of: :tweet
  accepts_nested_attributes_for :images,reject_if: proc{|b| b[:image].blank?}

  validates :content, presence: true
  validates :content, length: { maximum: 140 }

  def is_already_like(user)
  	#debugger
  	Like.where(user_id: user.id, tweet_id: id).exists?
  end

  def find_like(user)
  	likes.find_by(user_id: user.id)
  end

  def is_retweet(user)
    Retweet.where(user_id: user.id, tweet_id: id).exists?
  end

  def find_who_tweeted
    User.find_by(id: user_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
  has_one :image, as: :imageable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users

  has_many :likes, dependent: :destroy
  has_many :retweets, dependent: :destroy
  has_many :comments, dependent: :destroy

  def is_following(user)
  	followees.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

	 protected

  def configure_permitted_parameters
    if params[:controller].include?('sessions')
      devise_parameter_sanitizer.permit(:sign_in) do |user_params|
        user_params.permit(:user_name, :email)
      end
    else
      devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_tweet

  def new
  	@comment = Comment.new
  end

  def create
    #debugger
    @comment = current_user.comments.create(comment_params)
    # @comment = @tweet.comments.create(content: comment_params[:content], user_id: current_user.id)
    respond_to do |format|
      format.html
      format.js{}
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :tweet_id)
  end

  def find_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end
 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@users = User.page(params[:page]).per(3)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_tweet, only: [:create, :destroy]
  
  def index
  end

  def create
  	#debugger
    @like = @tweet.likes.create(user_id: current_user.id)
    #redirect_to tweets_path
    respond_to do |format|
      format.html
      format.js{}
    end
  end

  def show
  end

  def destroy
    @like = @tweet.likes.find(params[:id])
    @like.destroy
    respond_to do |format|
      format.html
      format.js{}
    end
  end
  
  private
  def find_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end

  def likes_params
  	params.require(:like).permit(:tweet_id, :user_id)
  end
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
before_action :find_tweet, only: [:create, :destroy]
  
  def index
  end

  def create
    if already_retweeted
      flash[:alert] = "Oops! you have already retweeted this tweet"
      redirect_to tweets_path
    else 
      @retweet = @tweet.retweets.create(user_id: current_user.id)
      flash[:alert] = "retweeted this tweet"
      respond_to do |format|
        format.html
        format.js{}
      end
    end
  end
  
  private
  def find_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end

  def already_retweeted
    Retweet.where(user_id: current_user.id, tweet_id: params[:tweet_id]).exists?
  end

  def retweet_params
  	params.require(:retweet).permit(:tweet_id, :user_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :find_tweet, except: [:new, :create, :index, :my_tweets]
  
  def index
    @tweets = Tweet.where(:user_id => current_user.followees).or(Tweet.where(user_id: current_user.id))#.or(Reweet.where(user_id: current_user.followees))
    #@tweets = Tweet.joins(user: :following_users).where(users: {follows: {follower_id: current_user.id}}).distinct
  	#@tweets = Tweet.all
  end

  def my_tweets
    #debugger
    # @tweets = Tweet.joins(:retweets).where(user_id: current_user.id , retweets: {user_id: current_user.id})
    @tweets = Tweet.left_outer_joins(:retweets).where("tweets.user_id=? or retweets.user_id=?", current_user.id, current_user.id).distinct
    #@tweets =Tweet.find_by_sql("SELECT * FROM tweets INNER JOIN retweets ON retweets.tweet_id = tweets.id WHERE tweets.user_id = 13 OR retweets.user_id = 13")
    #@tweets = Tweet.joins("INNER JOIN retweets ON tweets.id = retweets.user_id").where(user_id: current_user.id)
    #@tweets =  current_user.tweets
  end

  def new
  	@tweet = Tweet.new
    1.times { @tweet.images.build }
  end

  def create
  	#debugger
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
    	flash[:alert] = 'Here is your tweet'
    	redirect_to tweet_path(@tweet)
    else
    	flash[:alert] = "Sorry! unable to upload your tweet "
      #render 'new'
      redirect_to new_tweet_path
    end
  end

  def show
  end

  def edit
  end

  def update
  	if @tweet.update(tweet_params)
  		flash[:alert] = 'updated'
  		redirect_to tweet_path(@tweet)
  	else
  		render 'edit'
  	end
  end
  
  def destroy 
    if @tweet.destroy
    	flash[:alert] = "Successfully! tweet deleted"
    	redirect_to new_tweet_path
    else
    	flash[:alert] = "Sorry! Enable to delete your tweet"
    	redirect_to 
    end
  end
  private

  def find_tweet
    @tweet = current_user.tweets.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:content, images_attributes: [:id, :image, :imageable_type, :imageable_id, :_destroy ])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def follow
  	new_follow = current_user.followed_users.new(followee_id: params[:id])
  	if new_follow.save
  		flash[:alert] = 'followed successfully'
  	else
      flash[:alert] = 'Sorry! couldnt follow'
  	end
    redirect_to root_path
  end

  def unfollow
    follow = current_user.followed_users.find_by(followee_id: params[:id])
    if follow.destroy
      flash[:alert] = 'Successfullyy unfollowed'
    else
      flash[:alert] = 'Sorry! couldnt unfollow'
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/retweets_helper.rb
module RetweetsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

  def is_my_tweet(tweet)
    current_user.id == tweet.user_id 
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
   
end

app/views/comments/_comment.html.erb
<% user = comment.find_commenter %>
<span class="content"><b style="font-size: 13px"><%= user.user_name %><b>: <small><%= comment.content %></small></span>
<br/>

app/views/comments/create.js.erb
<% if @comment.persisted? %>
  var tweet_id = "<%= @tweet.id %>";
  $('#comments-'+tweet_id).append("<%= escape_javascript render(partial: '/comments/comment',  locals: {comment: @comment}) %>");
  $('.comment_text').val("");
<% end %>

app/views/home/index.html.erb
<table class="my-4 ml-4 table table-striped">
<tr>
  <th>User Name</th>
  <th>Email</th>
  <th>Suggestions</th>	
</tr>
  <% @users.each do |user| %>
      <% unless current_user == user %>
  	    <tr>
  		    <td><%= user.user_name %></td>
  		    <td><%= user.email %></td>
          <% if current_user.is_following(user) %>
            <td> <%= link_to 'Unfollow', unfollow_user_path(user), method: "POST" %> </td>
          <% else %>
            <td><%= link_to 'follow', follow_user_path(user), method: "POST" %></td>
          <% end%>
  	    </tr>
      <% end%>
  <% end %>
</table>
<%= paginate @users %>

app/views/likes/_likes.html.erb
<% if tweet.is_already_like(current_user) %>
  <% like = tweet.find_like(current_user) %>
	<%# like = tweet.likes.find_by(user_id: current_user.id) %>
	<%= link_to tweet_like_path(tweet, like), method: :delete, class: '', :remote => true do %>
	  <i class="fa fa-thumbs-up" aria-hidden="true"></i>
	<% end %>
<% else %>
	<%= link_to tweet_likes_path(tweet), method: :post, class: '', 
  :remote => true do %>
	  <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
	<% end %>
<% end %>
<span class="my-2 count" style="padding-right: 35px;"><%= tweet.likes.count %></span>

app/views/likes/create.js.erb
var tweet_id = "<%= @tweet.id %>";
$('#likes-'+tweet_id).html("<%= j render partial: '/likes/likes',  locals: {tweet: @tweet} %>");

app/views/likes/destroy.js.erb
var tweet_id = "<%= @tweet.id %>";
$('#likes-'+tweet_id).html("<%= j render partial: '/likes/likes',  locals: {tweet: @tweet} %>");

app/views/retweets/create.js.erb
$( ".flash-mesages" ).prepend( "<%= escape_javascript render(partial: '/shared/flash') %>");
$('.all-tweets').append("<%= escape_javascript render(partial: '/tweets/tweet', locals: {tweet: @tweet}) %>");
$('.count_retweets').html("<%= @tweet.retweets.count %>");

app/views/tweets/_comment.html.erb
<%= form_with model: @comment, url:'tweet_comments_path(tweet)', local: true do |f| %>
  <%#= debugger %>
  <%= f.text_field :content, class: 'form-control-sm com-content' %>
  <%= f.submit 'comment', class: "font-italic btn btn-sm btn-outline-info " %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="d-flex justify-content-center">
  <div class="bg-light border borger-light m-4 text-center p-4 max-width" >

    <div class="float-left my-0 align-baseline ">
      <i class="fa fa-user-circle-o fa-2x" aria-hidden="true"></i>
      <% user = tweet.find_who_tweeted %>
      <%if defined?(all_tweet) && all_tweet %>
        <%= user.user_name %>
      <% elsif tweet.is_retweet(current_user) %>
        <%= user.user_name %>,
        <i class="fa fa-retweet" aria-hidden="true"></i>
        <small> retweeted by you </small> 
      <% else %>
        <%= current_user.user_name %> 
      <% end %>
    </div><br><br>

    <% tweet.images.each do |image| %>    
      <%= image_tag image.image, style: "width:150px;height:100px;padding:10px;" %><br>
    <% end %>
    <b  style="font-size:29px; padding-bottom:0px;"><%= tweet.content %></b>


    <div style="padding-bottom:45px;" class="my-2">
      <% if is_my_tweet(tweet) %>
        <%# if params[:action].include?('my_tweets') %>
        <%= link_to 'edit', edit_tweet_path(tweet), class: 'btn btn-primary m-2' %>
        <%= link_to 'Destroy', tweet_path(tweet), method: :delete, class: 'btn btn-danger m-2' %> 
      <% else %>
	     	<span class="likes_count my-1 p-1" id="likes-<%= tweet.id %>">
          <%= render partial: "/likes/likes", locals: {tweet: tweet} %>
        </span>
        <%= link_to tweet_retweets_path(tweet), method: :post, class: '', :remote => true  do %>
          <i class="fa fa-retweet" aria-hidden="true"></i>
        <% end %>
        <span class=" my-2 count count_retweets">
          <%= tweet.retweets.count %>
        </span>
      <% end %>
      <br>
    </div>



	  <div class="text-align-left", id= "comments-<%= tweet.id %>">
	    <% tweet.comments.each do |comment| %> 
	      <%= render partial: "/comments/comment", locals: {comment: comment} %>
	    <% end %>
	  </div>
    <%= form_with model:[tweet, tweet.comments.build] , remote: true do |f| %>
      <%= f.text_field :content, class: 'form-control-sm comment_text' %>
      <%= f.submit 'comment', class: "font-italic btn btn-sm py-0 btn-outline-info comment text-center" %>
    <% end %>

    <%#= tweet.created_at %>
  </div> 
</div>

app/views/tweets/edit.html.erb
<div class=" mx-auto my-5 ml-auto border border-light bg-light p-4" style="width: 530px;" ">
<%= form_with model: @tweet, local: true do |f| %>
   
  <p> What's happning? </p>
  <p><%= f.text_area :content, class: 'w-75' %></p>
  <p><%= f.submit 'Tweet', class: 'btn btn-primary' %></p>

<% end %>
</div>

app/views/tweets/index.html.erb
<div class="all-tweets">
	<% @tweets.each do |tweet| %>
		<%#= render tweet %>
		<%= render partial: "tweet", locals: {tweet: tweet, all_tweet: true} %>
	<% end %>
</div>

app/views/tweets/my_tweets.html.erb
<% @tweets.each do |tweet| %>
  <%= render tweet %>
<% end %>
  

app/views/tweets/new.html.erb
<div class=" mx-auto my-5 ml-auto border border-light bg-light p-4" style="width: 530px;" ">
<%= form_with model: @tweet,html: {multipart: :true}, local: true do |f| %>
   
  <p> What's happning? </p>
  <p><%= f.text_area :content, class: 'w-75' %></p>
  <p>
  <%= f.fields_for :images do |image_form| %>
    <%= image_form.label :image %>
    <%= image_form.file_field :image, class: 'btn btn-outline-secondary' %>     
  <% end %></p>
  <p><%= f.submit 'Tweet', class: 'btn btn-primary' %></p>

<% end %>
</div>

app/views/tweets/show.html.erb
<%# @user.tweets.each do |t| %>
  <%#= t.content %>
  <%#= link_to 'edit', edit_tweet_path(t) %>
<%# end %>
<div class="mx-auto my-5 ml-auto border border-light bg-light p-4" style="width: 530px;">
  <p><%= @tweet.content %></p>
  <%= link_to 'edit', edit_tweet_path(@tweet), class: 'btn btn-primary m-3' %>
  <%= link_to 'Destroy', tweet_path(@tweet), method: :delete, class: 'btn btn-danger m-3' %>
  <%= link_to 'Show all tweets',  my_tweets_tweets_path, class: 'btn btn-primary m-3' %>
</div>